#!/usr/bin/env bash
# Deploy this repo's recyclarr config to grey and run it.
#
# The config here is authoritative. Before this existed, recyclarr.yml lived
# only on grey with API keys in plaintext, and any run would have reverted the
# quality policy applied through the API.
#
# Secrets never appear on a command line: keys live in recyclarr.env on grey
# (0600, uid 1001), generated by bootstrap-env below, and reach the container
# via --env-file.
set -euo pipefail

HOST="${GREY_HOST:-grey-area}"
REMOTE_CFG="/home/mk/grey-media/config/recyclarr"
IMAGE="ghcr.io/recyclarr/recyclarr:latest"
NETWORK="grey-media_default"
# Files are owned by mk (1001). The container defaults to another uid and then
# cannot read its own cached TRaSH checkout, failing with a bare "Access denied".
RUNAS="1001:1001"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() { echo "usage: $0 {bootstrap-env|deploy|preview|sync|regenerate}" >&2; exit 2; }
[ $# -ge 1 ] || usage

recyclarr() {
  ssh "$HOST" "docker run --rm --user $RUNAS --network $NETWORK \
    --env-file $REMOTE_CFG/recyclarr.env -v $REMOTE_CFG:/config $IMAGE $*"
}

case "$1" in
  bootstrap-env)
    # Extract each API key from the service's own config.xml server-side, so no
    # secret is ever transported through argv or this script's output.
    ssh "$HOST" 'python3 - <<EOF
import re, os
d = "/home/mk/grey-media/config"
def key(s):
    return re.search(r"<ApiKey>([^<]+)</ApiKey>", open("%s/%s/config.xml" % (d, s)).read()).group(1).strip()
p = "%s/recyclarr/recyclarr.env" % d
open(p, "w").write("RADARR_API_KEY=%s\nSONARR_API_KEY=%s\n" % (key("radarr"), key("sonarr")))
os.chmod(p, 0o600); os.chown(p, 1001, 1001)
print("wrote", p, "(0600)")
EOF'
    ;;
  deploy)
    scp -q "$HERE/recyclarr.yml" "$HOST:$REMOTE_CFG/recyclarr.yml"
    ssh "$HOST" "chown 1001:1001 $REMOTE_CFG/recyclarr.yml"
    echo "deployed recyclarr.yml -> $HOST"
    ;;
  preview) recyclarr sync --preview ;;
  sync)    recyclarr sync ;;
  regenerate)
    # Re-derive the YAML from live Radarr/Sonarr state after a profile has been
    # changed through the API, so the repo never drifts from the box.
    scp -q "$HERE/generate.py" "$HOST:/root/grey-ops/generate_recyclarr.py"
    ssh "$HOST" 'python3 /root/grey-ops/generate_recyclarr.py'
    scp -q "$HOST:/root/grey-ops/recyclarr.generated.yml" "$HERE/recyclarr.yml"
    echo "regenerated $HERE/recyclarr.yml from live state -- review the diff before committing"
    ;;
  *) usage ;;
esac
