#!/usr/bin/env python3
"""Regenerate the "current position" block in docs/canon/autonomy.md from state.

The canon page is the single definition of Sylveste's autonomy scales. Two of
the numbers on it are facts about the running system rather than definitions,
and hand-maintained numbers rot:

  * the declared human-delegation level  -> kernel state, via `ic autonomy status`
  * the A:L3 no-touch streak             -> `clavain-cli calibration-streak status`

This script reads both and rewrites the marked block. The kernel is not asked
about A:L3 and clavain-cli is not asked about delegation: each scale is read
from the layer that owns it, and the join happens here, at the repo level.

Usage:
  gen-autonomy-position.py                       # rewrite the block in place
  gen-autonomy-position.py --check               # exit 1 if the block is stale
  gen-autonomy-position.py --allow-unavailable   # render "unavailable" anyway

Exit codes: 0 current/rewritten, 1 stale (--check), 2 the sources could not be
read or the canon page is missing.

Why an unreadable source is exit 2 and not 0 or 1
-------------------------------------------------
`ic` lives in core/intercore, which the monorepo .gitignore's. On a cloud runner
the checkout has no kernel. Without one:

  * reporting "current" would compare an unavailable-block against an
    unavailable-block and pass — a green check that inspected nothing, the same
    vacuity trap that let 21 Kimi manifests drift (see
    .github/workflows/kimi-manifest-drift.yml);
  * reporting "stale" would be a lie: nothing was compared;
  * rewriting would overwrite a true block with "Current position: unavailable"
    and commit that.

So both modes stop at exit 2, "could not verify". `--allow-unavailable` opts
into the old rendering for the rare case where recording the gap is the point.

Real enforcement therefore runs in the pre-commit hook, where the monorepo is
materialised. CI's job is to prove this checker still refuses to report on a
source-less checkout, and to unit-test the rendering the hook depends on.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CANON = REPO_ROOT / "docs" / "canon" / "autonomy.md"

BEGIN = "<!-- BEGIN GENERATED: autonomy-position -->"
END = "<!-- END GENERATED: autonomy-position -->"

# Kept in sync with internal/autonomy.DefaultLevel. Duplicated deliberately:
# this script must still render something honest when `ic` is unavailable, and
# a wrong guess here is visible in the output rather than silent.
KERNEL_DEFAULT_LEVEL = 2


def resolve_bin(name: str) -> str | None:
    """Resolve a tool, honoring an explicit override.

    IC_BIN / CLAVAIN_CLI_BIN let this run against a freshly-built binary
    without installing it onto PATH first — the kernel change that adds
    `ic autonomy` ships before the binary is rolled out everywhere.
    """
    override = os.environ.get(name.upper().replace("-", "_") + "_BIN")
    if override:
        return override if os.path.isfile(override) else None
    return shutil.which(name)


def run(cmd: list[str]) -> str | None:
    """Run a command, returning stdout or None if it is unavailable/fails."""
    resolved = resolve_bin(cmd[0])
    if resolved is None:
        return None
    cmd = [resolved] + cmd[1:]
    try:
        proc = subprocess.run(
            cmd, cwd=REPO_ROOT, capture_output=True, text=True, timeout=30
        )
    except (subprocess.TimeoutExpired, OSError):
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout.strip()


def delegation() -> dict:
    """Read the declared delegation level from kernel state."""
    out = run(["ic", "--json", "autonomy", "status"])
    if not out:
        return {"available": False}
    try:
        data = json.loads(out)
    except json.JSONDecodeError:
        return {"available": False}
    data["available"] = True
    return data


def streak() -> str | None:
    """Read the A:L3 no-touch streak from the OS layer."""
    out = run(["clavain-cli", "calibration-streak", "status"])
    return out or None


# Sentinel for "argument not supplied". None cannot serve: for the streak it is
# a real value meaning "no streak reported", and conflating the two made a
# caller asking for a streak-less render get a live reading instead.
_UNSET = object()


def render(d=_UNSET, s=_UNSET) -> str:
    """Render the block from two source readings.

    Both readings are parameters rather than calls so the rendering can be
    tested without a kernel present — which is the only part of this script a
    plugin-less CI checkout can meaningfully exercise.
    """
    if d is _UNSET:
        d = delegation()
    if s is _UNSET:
        s = streak()
    lines: list[str] = [BEGIN, ""]
    lines.append("<!-- Regenerated by scripts/gen-autonomy-position.py. Do not hand-edit. -->")
    lines.append("")

    if not d.get("available"):
        lines.append(
            "**Current position: unavailable.** `ic` could not be reached when this "
            "block was generated, so no live value is recorded here. Run "
            "`scripts/gen-autonomy-position.py` on a machine with the kernel installed."
        )
    elif d.get("declared"):
        lines.append(
            f"**Declared delegation level: L{d['level']}** — {d['name']}. "
            f"New runs inherit `auto_advance={str(d['derives_auto_advance']).lower()}`."
        )
    else:
        lines.append(
            f"**Delegation level: not declared.** The kernel falls back to "
            f"L{d['level']} ({d['name']}), so new runs inherit "
            f"`auto_advance={str(d['derives_auto_advance']).lower()}`."
        )
        lines.append("")
        lines.append(
            "> This is the honest state, not a placeholder. Prose across the repo "
            "has long said \"currently operating at L1–L2\", but a band is not a "
            "machine fact and nothing ever recorded which rung was in force. "
            "Declare one with `ic config set autonomy.delegation_level <0-5>`."
        )

    if s:
        lines.append("")
        lines.append(f"**Track A evidence:** `{s}`")
        lines.append("")
        lines.append(
            "Track levels are earned, never set — this is evidence that may justify "
            "a delegation decision, not a delegation level itself (see §5, §7)."
        )

    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(text):
        raise SystemExit(
            f"error: markers not found in {CANON.relative_to(REPO_ROOT)}\n"
            f"       expected a block delimited by:\n         {BEGIN}\n         {END}"
        )
    return pattern.sub(lambda _: block, text)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the block is stale instead of rewriting it",
    )
    ap.add_argument(
        "--allow-unavailable",
        action="store_true",
        help="render 'Current position: unavailable' instead of exiting 2 when "
        "the kernel cannot be reached",
    )
    args = ap.parse_args()

    if not CANON.exists():
        print(f"error: {CANON} does not exist", file=sys.stderr)
        return 2

    d = delegation()
    if not d.get("available") and not args.allow_unavailable:
        verb = "verify" if args.check else "regenerate"
        print(
            f"error: cannot {verb} the autonomy position block — "
            "`ic autonomy status` is unreachable,\n"
            "       so the declared delegation level could not be read. This is "
            "not 'stale' and not\n"
            "       'current': nothing was compared. Set IC_BIN, run where "
            "core/intercore is\n"
            "       materialised, or pass --allow-unavailable to record the gap "
            "deliberately.",
            file=sys.stderr,
        )
        return 2

    current = CANON.read_text(encoding="utf-8")
    updated = splice(current, render(d, streak()))

    if current == updated:
        print("autonomy position block is current")
        return 0

    if args.check:
        print(
            "autonomy position block is STALE — run scripts/gen-autonomy-position.py",
            file=sys.stderr,
        )
        return 1

    CANON.write_text(updated, encoding="utf-8")
    print(f"rewrote autonomy position block in {CANON.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
